name: react-testing

on: [ push ]

jobs:
  execute_tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: yarn install
      - name: execute unit tests
        run: yarn run test
      - name: build storybook
        run: yarn build-storybook --quiet
      - name: Serve Storybook and run tests
        run: yarn test-storybook:ci